#!/bin/sh

WSN="0:WORKSPACE"
WSF=$(echo $WSN | sed "s/:/_/g" | sed -E "s/^([0-9]_)/0\1/g")

# To avoid back-and-forth, switch to a non-existent workspace
# before switching to and applying the layout. This is not
# needed for singular restores, but is needed for batch.
if [ $("/home/brian/.local/share/bin/i3-get-workspace") == "$WSN" ]; then
	PREFIX="workspace \"NonExistentWorkspace\";"
else
	PREFIX=""
fi

i3-msg "$PREFIX workspace $WSN; append_layout ~/.config/i3/workspaces/$WSF.json"
sleep 1

# Application Launchers

