#!/bin/sh

CLASS_SITE="http://www.mattbowytz.com/cs1520.php"
PROJ_REPO="https://github.com/RedSoxFan/2174-CS1520-Project"
PROJ_URL="file:///home/brian/OneDrive/Pitt/2174/1520/project/index.html"

WSN="5:1520"
WSF=$(echo $WSN | sed "s/:/_/g" | sed -E "s/^([0-9]_)/0\1/g")

# To avoid back-and-forth, switch to a non-existant workspace
# before switching to and applying the layout. This is not
# needed for singular restores, but is needed for batch.
if [ $("/home/brian/.local/share/bin/i3-get-workspace") == "$WSN" ]; then
	PREFIX="workspace \"NonExistantWorkspace\";"
else
	PREFIX=""
fi

i3-msg "$PREFIX workspace $WSN; append_layout ~/.config/i3/workspaces/$WSF.json"
sleep 1
vivaldi-stable --new-window $CLASS_SITE $PROJ_REPO $PROJ_URL &
urxvt -name webapps -e sh -c "cd ~/OneDrive/Pitt/2174/1520/project && zsh" &
