#!/bin/sh
CLASS_REPO="https://github.com/laboon/CS1632_Spring2017"
PROJ_REPO=""
PROJ_DIR=""

WSN="7:1632"
WSF=$(echo $WSN | sed "s/:/_/g" | sed -E "s/^([0-9]_)/0\1/g")

# To avoid back-and-forth, switch to a non-existant workspace
# before switching to and applying the layout. This is not
# needed for singular restores, but is needed for batch.
if [ $("i3-get-workspace") == "$WSN" ]; then
	PREFIX="workspace \"NonExistantWorkspace\";"
else
	PREFIX=""
fi

i3-msg "$PREFIX workspace $WSN; append_layout ~/.config/i3/workspaces/$WSF.json"
sleep 1
vivaldi-stable --new-window $CLASS_REPO $PROJ_REPO &
urxvt -name quality -e sh -c "cd ~/OneDrive/Pitt/2174/1632 && cd $PROJ_DIR && zsh" &
